{% set name = "opentelemetry-propagator-jaeger" %}
{% set version = "1.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry-propagator-jaeger-{{ version }}.tar.gz
  sha256: af3f16b5fc9adc697b5ca9b989c44f35c3a3b4cb23a083f0a18a10a7fe2211be

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - opentelemetry-api ~=1.3
    - python >=3.6

test:
  imports:
    - opentelemetry
    - opentelemetry.propagators
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python/tree/main/propagator/opentelemetry-propagator-jaeger
  summary: OpenTelemetry Jaeger Propagator
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
